### ISSUE TITLE
CRA is unmaintained

### ISSUE THREAD

**Issue by PrettyCoffee** [alan2207/bulletproof-react#151]
I just found this and it looks like a really valuable ressource!

However, using CRA (+ Craco) is really outdated as CRA is no longer being maintained.

If someone starts a react project based on this repo without knowing this, it will lead to problems and headaches for them.

Given you are open to migrating to Vite (which kind of is the current standard), I could look into it and raise a PR for that.

**Comment by alan2207** [comment]
Hey @PrettyCoffee ,

Thanks a lot for raising this issue, I absolutely agree and have planned to do that in the near future, probably in the next couple of months. It's a bit challenging though to just do that update without updating other things since there a re a lot of new packages and breaking changes, so the updates should probably arrive in bulk in the next couple of months.

If you manage to migrate from CRA to Vite without breaking other things, feel free to submit a PR.

**Comment by alan2207** [comment]
This can be closed due to https://github.com/alan2207/bulletproof-react/pull/152 being merged.

**Comment by PrettyCoffee** [comment]
@alan2207 Thanks for putting all the effort into the update! :)
