### ISSUE TITLE
What is the src/lib directory used for?

### ISSUE THREAD

**Issue by ahhshm** [alan2207/bulletproof-react#2]
I have seen the src/lib directory in many projects but I have no idea why we should use it.

For example, in this project, you put the authorization.tsx file in this directory, it could be in the utils or hooks or even components directory. (I haven't read this project completely and maybe I'm wrong but you get the point.)

Can someone explain to me exactly what files should be placed in it? sometimes even functions and hooks are placed in this directory, when we should do this?

**Comment by alan2207** [comment]
I like to put internal or external libraries inside the `lib` folder. 

External libraries such as axios HTTP client can be configured there and then re-exported. 

The`authorization.tsx` file is inside lib because it could be considered as an internal library. Why is it not in utils/hooks/components? Because it is a module that exports multiple things and it wouldn't fit in other folders such as hooks because it exports the `Authorization` component, and it is not in the components folder because it exports the `useAuthorization` hook plus some other things.

**Comment by ahhshm** [comment]
Thank you. That makes sense to me.
