### ISSUE TITLE
Some Typescript declare cannot easy to understand

### ISSUE THREAD

**Issue by dim0147** [alan2207/bulletproof-react#48]
Hi, this is a good overview of the real project, but sometimes I can't understand much about TypeScript declare in some files, for example in the [https://github.com/alan2207/bulletproof-react/blob/master/src/components/Form/Form.tsx](https://github.com/alan2207/bulletproof-react/blob/master/src/components/Form/Form.tsx):
```

type FormProps<TFormValues, Schema> = {
  className?: string;
  onSubmit: SubmitHandler<TFormValues>;
  children: (methods: UseFormReturn<TFormValues>) => React.ReactNode;
  options?: UseFormProps<TFormValues>;
  id?: string;
  schema?: Schema;
};

export const Form = <
  TFormValues extends Record<string, unknown> = Record<string, unknown>,
  Schema extends ZodType<unknown, ZodTypeDef, unknown> = ZodType<unknown, ZodTypeDef, unknown>
>({
  onSubmit,
  children,
  className,
  options,
  id,
  schema,
}: FormProps<TFormValues, Schema>) => {
  const methods = useForm<TFormValues>({ ...options, resolver: schema && zodResolver(schema) });
  return (
    <form>
```
- The part
 ```
<
  TFormValues extends Record<string, unknown> = Record<string, unknown>,
  Schema extends ZodType<unknown, ZodTypeDef, unknown> = ZodType<unknown, ZodTypeDef, unknown>
>
```
really confuse me, do we need to understand clearly those declarations? Thanks

**Comment by alan2207** [comment]
Hi @dim0147 ,

In this part, we are utilizing TypeScript generics in order to parameterize the types.

This is the way to pass the types down to some inner part of the code, in this example to the `useForm` hook which is also a generic. It needs to be dynamic because for different forms you will have different data types which must be passed to the `useForm` hook from the outside.

More info:
https://www.freecodecamp.org/news/make-typescript-easy-using-basic-ts-generics/
https://www.benmvp.com/blog/generic-react-components-typescript/
https://mariusschulz.com/blog/passing-generics-to-jsx-elements-in-typescript
