### ISSUE TITLE
Where should tests be located?

### ISSUE THREAD

**Issue by ColinCee** [alan2207/bulletproof-react#52]
Looking at the [project structure](https://github.com/alan2207/bulletproof-react/blob/master/docs/project-structure.md)

I quickly glanced and saw there was a test directory but it seems to be only for 

```
+-- test              # test utilities and mock server
```

When navigating to the [test folder](https://github.com/alan2207/bulletproof-react/tree/master/src/test) in this repo I see its mainly support files.

Looking around I can see [some directories](https://github.com/alan2207/bulletproof-react/tree/master/src/components/Head) have a `__tests__`  directory within the `components/XXX` directory. Whilst [some do not](https://github.com/alan2207/bulletproof-react/tree/master/src/components/Layout)

--- 

Is having a `__tests__` directory the recommended approach then?

Currently we're split between using two different approaches for where to store our tests:

1. `projectRoot/tests`
2. Place the corresponding `*.test.tsx` file for next to the component in src

The problem with `1.` is that depending on how large the codebase is, it can be hard to find the corresponding test.
The problem with `2.` is that it quickly clutters any directory as the number of files quickly doubles since each component now has a test file.

**Comment by alan2207** [comment]
Inside the `src/test`folder, we are just adding a baseline for all the tests including mocks, generators, test utilities etc. which are used inside all tests, to avoid repetition for each test. 

Some components do not have `__tests__` because not every component is required to be tested, sometimes you want to test only the most critical parts of the application, but that also depends on the requirements of the application.

You are right about the pros and cons of both approaches. I prefer the second one to keep my tests as close as possible to the code I am testing. On the other hand having too many `*.test.tsx` files might clutter your folders. As a compromise I like to have `__tests__` folder in the same folder where the code is located like following:

`src/components/MyComponent.tsx`

and then test would be in:
`src/components/__tests__/MyComponent.test.tsx`

Now imagine having a lot of the components, you can still quickly browse the code files as you did before, but if you are interested in tests, just enter the `__tests__` folder.

One more option is to place every component in a folder like this:
`src/components/MyComponent/MyComponent.tsx`
`src/components/MyComponent/MyComponent.test.tsx`
`src/components/MyComponent/index.ts`

Which one should you choose? Whichever makes more sense to you and your team, just keep it consistent afterward.

**Comment by ColinCee** [comment]
Hey Alan, thanks for your suggestion, I've spoken to the team and we're leaning towards the `__tests__` folder for each directory. This will apply to not just components directory but any `utils` directory or whatever that's not a component

Finally I do very much agree on having consistency, thanks a lot for the discussion!
