### ISSUE TITLE
Enable discussions on this repository

### ISSUE THREAD

**Issue by ryota-murakami** [alan2207/bulletproof-react#7]
I've really empathize these README section.

> The goal of this repo is to serve as a collection of good practices when developing React applications. It is supposed to showcase solving most of the real-world problems of an application in a practical way and help developers writing better applications.

I have a project [create-react-app-typescript-todo-example-2021](https://github.com/laststance/create-react-app-typescript-todo-example-2021) on similar mind,(It's not high quality though 😅)  

And @markerikson also planed close concept website [**React Community Tools and Practices Cheatsheet**](https://github.com/markerikson/react-community-tools-practices-cheatsheet) .

I like those project even though this topic contained a lot of subjective things.  
I hope to we got space for exchange information about practice that doesn't matter each developer's preference/style/opinion.  

Actually I don't know ideal roadmap to the goal even though this repository showing Github trend page these days,
So if Github Discussions available visitors may create some topics or answer some questions or surveys, and the communication of information exchange may flourish.

Do you have a plan about setup Discussions on here? 👨‍💻

**Comment by alan2207** [comment]
Hey, that is a great idea!

It had crossed my mind to enable discussions too. That would be a nice way to discuss different solutions in more detail since not everything can fit in a single codebase. I might enable it soon.

Another thing I am considering is creating a documentation website based on [Docusaurus](https://docusaurus.io/) or [Nextra](https://nextra.vercel.app/) where all the best explanations and resources could be found easily, but that could happen if the docs become larger.

**Comment by markerikson** [comment]
FWIW, that's exactly what I've already tried to create in that "community tools and practices" site:

https://github.com/markerikson/react-community-tools-practices-cheatsheet/discussions/1

https://react-community-tools-practices-cheatsheet.netlify.app/state-management/overview

The problem is I don't have time to put into actually adding more content to it right now, and I really want that to be a _community_-maintained site - not just a "Mark sat down and wrote a dozen docs pages" thing.  

Thus far, no one else has actually contributed any material, although a few folks have expressed interest.

**Comment by alan2207** [comment]
Now that I took a quick look at the repo @markerikson made, I think it might be a more suitable resource for community-based content because he already made a solid base for that. Another reason is that bulletproof-react might be a bit opinionated and I want it to stay that way, at least for now.

**Comment by marcustut** [comment]
@alan2207 I have successfully set up a project according to opinions made in bulletproof-react, but I swap the build system to Vite and Tailwind to WindiCSS, it's building blazingly fast.

Maybe we could mention about the build system in this [section](https://github.com/alan2207/bulletproof-react/blob/master/docs/project-configuration.md)?

**Comment by ryota-murakami** [comment]
It's might be too late, thank you for enabled discussion @alan2207 🤗
I'm considering should I close this issue or stay open mean while because
@markerikson 's [platform](https://react-community-tools-practices-cheatsheet.netlify.app/state-management/overview) doesn't seem kicked off.
Can I fill out from basic part like `starter` Next.js, Vite, CRA etc...?

**Comment by ryota-murakami** [comment]
There is no topics number badge as same as Issue and PR tabs, Hence, Discussion tabs cannot get people's pay attention? 😅
