### ISSUE TITLE
Suggestion: merge tsconfig.paths.json into tsconfig.json

### ISSUE THREAD

**Issue by DoctorDerek** [alan2207/bulletproof-react#9]
Hey, I'm happy to open a PR to do this quick chore. 

I'm not sure why https://github.com/alan2207/bulletproof-react/blob/master/tsconfig.paths.json is a separate file. 

To me, it's less clear if anything. And the mandatory clutter (config files) we have is plenty already, right?

I'd never expect to find the paths hanging out in a separate file, though I'd surely notice it.

Feel free to close the issue if you don't approve! Have a good one!

**Comment by alan2207** [comment]
Although I agree with you on this 100%, it is unfortunately required by CRA, otherwise, it will override it every time. 
There are several issues on github on CRA project about it. Here is one of them: https://github.com/facebook/create-react-app/issues/8909 

I also mentioned it briefly here: https://github.com/alan2207/bulletproof-react/blob/master/docs/project-configuration.md

So for now, let's keep it this way, but thanks anyway :)

**Comment by DoctorDerek** [comment]
Cool thanks for the note @alan2207 I don't use CRA myself. Cheers!
